name: Prueba de Workflow con PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Workflow Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./python
